
program = feFRAC

subdirs = ../src/util  ../src/material ../src/model ../src/module ../src/femodel 

include $(JIVEDIR)/makefiles/prog.mk
include $(JIVEDIR)/makefiles/packages/*.mk

SYS_LIBDIRS = /usr/local/lib/ 

MY_INCDIRS = /Users/vingu/my-codes/ofeFRAC/src /usr/local/include #/usr/local/include/vtk-7.1
MY_CXX_STD_FLAGS=-stdlib=libc++ -std=c++11
MY_CXX_LNK_FLAGS=-lc++ #-lvtkCommonDataModel-7.1.1 -lvtkCommonCore-7.1.1 -lvtkIOXML-7.1.1
